### ISSUE TITLE
Mover los estilos a una carpeta

### ISSUE THREAD

**Issue by Keikooh** [Keikooh/ExpressFrontend#1]
Mover los **const style** a la carpeta de **styles** en **assets** y exportarlos
![image](https://user-images.githubusercontent.com/112024156/233400162-5eeb31d0-8493-46d8-835b-f7340e2b2286.png)

**Comment by Carlos-Centeno14** [comment]
Esa mamada q

**Comment by Carlos-Centeno14** [comment]
El internet del Tec no jala, buenos pa hacer huelga pero pa poner buen
internet nada
